### ISSUE TITLE
The return of 'This TextEditor has been destroyed'

### ISSUE THREAD

**Issue by andrewvc** [avendael/atomic-emacs#105]
I'm getting this error, same as in https://github.com/avendael/atomic-emacs/issues/76 and it seems for the same reasons. This happens after I've been editing for a while. Restarting atom fixes it.

[Enter steps to reproduce below:]

I've experienced this with a split editor. I don't actually need to alter the contents of the second pane, just execute any keystroke (like the up arrow).

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.4
**Thrown From**: [atomic-emacs](https://github.com/avendael/atomic-emacs) package, v0.9.1

### Stack Trace

Uncaught Error: This TextEditor has been destroyed

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:794

Error: This TextEditor has been destroyed
    at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:794:15)
    at DisplayBuffer.module.exports.DisplayBuffer.screenRangeForBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:758:20)
    at TextEditorMarker.module.exports.TextEditorMarker.getScreenRange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-marker.js:141:33)
    at Selection.module.exports.Selection.getScreenRange (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:78:26)
    at Selection.module.exports.Selection.autoscroll (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:965:53)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:109:19
    at Selection.module.exports.Selection.modifySelection (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:978:7)
    at Selection.module.exports.Selection.setBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:100:19)
    at Mark.setSelectionRange (/Users/andrewvc/.atom/packages/atomic-emacs/lib/mark.coffee:97:23)
    at Mark._updateSelection (/Users/andrewvc/.atom/packages/atomic-emacs/lib/mark.coffee:88:10)
    at /Users/andrewvc/.atom/packages/atomic-emacs/lib/mark.coffee:53:10
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:270:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:30.1.0 atomic-emacs:backward-kill-word (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:19.3.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:19.1.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:19.1.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:19 atomic-emacs:previous-line (atom-text-editor.editor.is-focused)
     -0:12.5.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:12.3.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:12.3.0 core:cancel (atom-text-editor.editor.is-focused)
  4x -0:12.1.0 atomic-emacs:previous-line (atom-text-editor.editor.is-focused)
     -0:11.2.0 editor:move-to-beginning-of-line (atom-text-editor.editor.is-focused)
  2x -0:10.9.0 atomic-emacs:kill-line (atom-text-editor.editor.is-focused)
     -0:10.5.0 atomic-emacs:previous-line (atom-text-editor.editor.is-focused)
     -0:10.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:08.7.0 atomic-emacs:close-other-panes (atom-text-editor.editor.is-focused)
  3x -0:07.1.0 atomic-emacs:next-line (atom-text-editor.editor.is-focused)
  4x -0:00.6.0 atomic-emacs:previous-line (atom-text-editor.editor.is-focused)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
atomic-emacs, v0.9.1
file-icons, v1.7.11
tidy-tabs, v0.3.0

# Dev
No dev packages
```

**Comment by oggy** [comment]
Thanks for the report. I'm pretty sure I've seen this too, but have been unable to isolate precise repro steps. I'll keep my eyes peeled.

**Comment by oggy** [comment]
Note to self: this happens when you `set-mark` then close the tab.
