### ISSUE TITLE
this.editor.onDidRemoveCursor is not a function

### ISSUE THREAD

**Issue by dwwoelfel** [avendael/atomic-emacs#117]
[Enter steps to reproduce below:]

1. Hit Ctrl+K, then Ctrl+Y

**Atom Version**: 1.12.2
**Electron Version**: 1.3.6
**System**: Mac OS X 10.11.6
**Thrown From**: [atomic-emacs](https://github.com/avendael/atomic-emacs) package, v0.9.2

### Stack Trace

Uncaught TypeError: this.editor.onDidRemoveCursor is not a function

```
At /Users/dww/.atom/packages/atomic-emacs/lib/emacs-editor.coffee:12

TypeError: this.editor.onDidRemoveCursor is not a function
  at new EmacsEditor (/Users/dww/.atom/packages/atomic-emacs/lib/emacs-editor.coffee:12:27)
  at Function.module.exports.EmacsEditor.for (/Users/dww/.atom/packages/atomic-emacs/lib/emacs-editor.coffee:9:32)
  at getEditor (/Users/dww/.atom/packages/atomic-emacs/lib/atomic-emacs.coffee:27:3)
  at afterCommand (/Users/dww/.atom/packages/atomic-emacs/lib/atomic-emacs.coffee:15:19)
  at /Users/dww/.atom/packages/atomic-emacs/lib/atomic-emacs.coffee:48:60
  at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:269:20)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
  at AICompleteProvider._closeCodeSnippetView (/opt/facebook/nuclide/0.181.43492191/nuclide/pkg/fb-ai-complete/lib/AICompleteProvider.js:134:19)
  at _subscriptions.add._autocompleteManager.suggestionList.onDidChangeItems.items (/opt/facebook/nuclide/0.181.43492191/nuclide/pkg/fb-ai-complete/lib/AICompleteProvider.js:383:14)
  at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
  at SuggestionList.module.exports.SuggestionList.changeItems (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/suggestion-list.js:323:27)
  at AutocompleteManager.module.exports.AutocompleteManager.hideSuggestionList (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:560:27)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:59

```

### Commands

```
     -0:02.0 atomic-emacs:next-line (atom-text-editor.editor.is-focused)
     -0:02.0 fb-code-snippet-view:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-light-syntax.theme-one-light-ui.atomic-emacs)
     -0:01.7.0 editor:move-to-beginning-of-line (atom-text-editor.editor.is-focused)
     -0:01.7.0 fb-code-snippet-view:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-light-syntax.theme-one-light-ui.atomic-emacs)
     -0:01.5.0 atomic-emacs:next-line (atom-text-editor.editor.is-focused)
     -0:01.5.0 fb-code-snippet-view:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-light-syntax.theme-one-light-ui.atomic-emacs)
     -0:01.3.0 atomic-emacs:forward-char (atom-text-editor.editor.is-focused)
     -0:01.3.0 fb-code-snippet-view:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-light-syntax.theme-one-light-ui.atomic-emacs)
     -0:01.1.0 atomic-emacs:forward-char (atom-text-editor.editor.is-focused)
     -0:01.1.0 fb-code-snippet-view:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-light-syntax.theme-one-light-ui.atomic-emacs)
     -0:00.9.0 atomic-emacs:forward-char (atom-text-editor.editor.is-focused)
     -0:00.9.0 fb-code-snippet-view:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-light-syntax.theme-one-light-ui.atomic-emacs)
     -0:00.4.0 atomic-emacs:kill-line (atom-text-editor.editor.is-focused)
     -0:00.4.0 fb-code-snippet-view:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-light-syntax.theme-one-light-ui.atomic-emacs)
     -0:00.2.0 atomic-emacs:yank (atom-text-editor.editor.is-focused)
  2x -0:00.2.0 fb-code-snippet-view:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-light-syntax.theme-one-light-ui.atomic-emacs)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "automaticallyUpdate": false,
    "customFileTypes": {
      "source.cpp": [
        "h"
      ],
      "source.ini": [
        ".buckconfig",
        ".flowconfig",
        ".hgrc"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "TARGETS",
        "cconf",
        "cinc",
        "mcconf",
        "tw",
        "BUCK",
        "ctw",
        "thrift-cvalidator"
      ]
    },
    "disabledPackages": [
      "deprecation-cop",
      "fuzzy-finder",
      "metrics",
      "tree-view",
      "styleguide",
      "timecop",
      "linter"
    ],
    "openEmptyEditorOnStart": false,
    "telemetryConsent": "no",
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atomic-emacs, v0.9.2 (active)
haskell-grammar, v0.4.0 (active)
highlight-selected, v0.11.2 (active)
language-babel, v2.38.0 (active)
language-ini, v1.16.0 (active)
language-ocaml, v1.1.2 (active)
language-swift, v0.4.0 (active)
language-thrift, v1.0.2 (active)
linter, v1.11.18 (inactive)
linter-eslint, v8.0.0 (active)
merge-conflicts, v1.4.4 (active)
nuclide, v0.181.43492191 (active)
nuclide-format-js, v0.0.36 (inactive)
sort-lines, v0.14.0 (inactive)
tool-bar, v1.0.1 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (inactive)
one-light-ui, v1.6.2 (active)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (active)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (active)
fuzzy-finder, v1.4.0 (inactive)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.1 (inactive)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (inactive)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (inactive)
tree-view, v0.210.0 (inactive)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.46.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by rjbailey** [comment]
I am also seeing this issue.
