### ISSUE TITLE
Uncaught TypeError: this.editor.onDidRemoveCursor is not a function

### ISSUE THREAD

**Issue by danmuriello** [avendael/atomic-emacs#122]
Yank commands result in "Uncaught TypeError: this.editor.onDidRemoveCursor is not a function" errors

[Enter steps to reproduce below:]

1. Kill a line
2. Yank it onto another line

**Atom Version**: 1.13.0
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.2
**Thrown From**: [atomic-emacs](https://github.com/avendael/atomic-emacs) package, v0.9.2

### Stack Trace

Uncaught TypeError: this.editor.onDidRemoveCursor is not a function

```
At /Users/danmuriello/.atom/packages/atomic-emacs/lib/emacs-editor.coffee:12

TypeError: this.editor.onDidRemoveCursor is not a function
  at new EmacsEditor (/Users/danmuriello/.atom/packages/atomic-emacs/lib/emacs-editor.coffee:12:27)
  at Function.module.exports.EmacsEditor.for (/Users/danmuriello/.atom/packages/atomic-emacs/lib/emacs-editor.coffee:9:32)
  at getEditor (/Users/danmuriello/.atom/packages/atomic-emacs/lib/atomic-emacs.coffee:27:3)
  at afterCommand (/Users/danmuriello/.atom/packages/atomic-emacs/lib/atomic-emacs.coffee:15:19)
  at /Users/danmuriello/.atom/packages/atomic-emacs/lib/atomic-emacs.coffee:48:60
  at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:269:20)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
  at AICompleteProvider._closeCodeSnippetView (/opt/facebook/nuclide/0.197.47211038/nuclide/pkg/fb-ai-code-search/lib/AICompleteProvider.js:133:19)
  at _subscriptions.add._autocompleteManager.suggestionList.onDidChangeItems.items (/opt/facebook/nuclide/0.197.47211038/nuclide/pkg/fb-ai-code-search/lib/AICompleteProvider.js:382:14)
  at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
  at SuggestionList.changeItems (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/suggestion-list.js:344:27)
  at AutocompleteManager.hideSuggestionList (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:613:27)

```

### Commands

```
  2x -0:02.8.0 fb-code-snippet-view:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui.atomic-emacs)
     -0:02.4.0 editor:move-to-beginning-of-line (input.hidden-input)
     -0:02.4.0 fb-code-snippet-view:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui.atomic-emacs)
     -0:02.1.0 atomic-emacs:set-mark (input.hidden-input)
     -0:02.0 atomic-emacs:next-line (input.hidden-input)
     -0:02.0 fb-code-snippet-view:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui.atomic-emacs)
     -0:01.8.0 atomic-emacs:kill-region (input.hidden-input)
     -0:01.8.0 fb-code-snippet-view:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui.atomic-emacs)
     -0:00.9.0 atomic-emacs:previous-line (input.hidden-input)
     -0:00.9.0 fb-code-snippet-view:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui.atomic-emacs)
     -0:00.7.0 atomic-emacs:previous-line (input.hidden-input)
     -0:00.7.0 fb-code-snippet-view:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui.atomic-emacs)
     -0:00.6.0 atomic-emacs:previous-line (input.hidden-input)
     -0:00.6.0 fb-code-snippet-view:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui.atomic-emacs)
     -0:00.3.0 atomic-emacs:yank (input.hidden-input)
  2x -0:00.3.0 fb-code-snippet-view:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui.atomic-emacs)
```

### Config

```json
{
  "core": {
    "automaticallyUpdate": false,
    "customFileTypes": {
      "source.cpp": [
        "h"
      ],
      "source.ini": [
        ".buckconfig",
        ".hgrc",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "TARGETS",
        "cconf",
        "cinc",
        "ctw",
        "mcconf",
        "tw",
        "thrift-cvalidator",
        "BUCK"
      ]
    },
    "disabledPackages": [
      "metrics",
      "autocomplete",
      "deprecation-cop",
      "styleguide",
      "timecop",
      "fuzzy-finder",
      "tree-view"
    ],
    "telemetryConsent": "no"
  }
}
```

### Installed Packages

```coffee
# User
atomic-emacs, v0.9.2 (active)
haskell-grammar, v0.4.0 (active)
highlight-selected, v0.12.0 (active)
language-babel, v2.49.4 (active)
language-graphql, v0.8.0 (active)
language-ini, v1.17.0 (active)
language-lua, v0.9.11 (active)
language-ocaml, v1.1.2 (active)
language-swift, v0.5.0 (active)
language-thrift, v1.0.2 (active)
merge-conflicts, v1.4.4 (active)
nuclide, v0.197.47211038 (active)
nuclide-format-js, v0.0.36 (inactive)
set-syntax, v0.3.2 (active)
sort-lines, v0.14.0 (inactive)
tool-bar, v1.0.1 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (active)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (active)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (inactive)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (inactive)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.1.2 (inactive)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (inactive)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (inactive)
tree-view, v0.211.1 (inactive)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by cyandterry** [comment]
Same issue here

**Comment by oggy** [comment]
I was never able to repro this using the steps above, but I pushed a fix for a similar looking error in 0.10.0. Let me know if you're still seeing this there.

Thanks for reporting!

**Comment by dwwoelfel** [comment]
I still see this error after updating. I can get rid of the error if I restart Atom, but I'll get the error every time I kill and yank until I restart. 

It doesn't break the functionality as far as I can tell, it just throws an error.

https://gist.github.com/dwwoelfel/26ba3d7735c3821808fbf5115cbc10eb

**Comment by akanter** [comment]
I also have been getting this issue consistently. Functionality seems fine, but it pukes error messages every time I yank.

**Comment by zopu** [comment]
I'm also seeing this on 0.10.0.

Atom 1.15.0 x64 (OS X Sierra).

**Comment by zopu** [comment]
Here's the stacktrace for me:
https://gist.github.com/zopu/5b8deb1b8815ec063405537bcf171ff6

**Comment by cyandterry** [comment]
Same issue as well. Here's the gist paste https://gist.github.com/cyandterry/6fb3d851f46fba5fa0c204e77173b7e1

**Comment by david-y-lam** [comment]
+1

**Comment by patrickshuff** [comment]
+1
