### ISSUE TITLE
Uncaught TypeError: Cannot read property 'start' of null

### ISSUE THREAD

**Issue by mrhota** [avendael/atomic-emacs#47]
[Enter steps to reproduce below:]

1. Open a file which does not end with a newline. This happened in .java, .js, and a handlebars template file (.tpl).
2. Try skipping to end of file with alt+} (forward paragraph)

**Atom Version**: 0.187.0
**System**: Mac OS X 10.9.5
**Thrown From**: [atomic-emacs](https://github.com/avendael/atomic-emacs) package, v0.4.0

### Stack Trace

Uncaught TypeError: Cannot read property 'start' of null

```
At /Users/____/.atom/packages/atomic-emacs/lib/atomic-emacs.coffee:224

TypeError: Cannot read property 'start' of null
  at AtomicEmacs.forwardParagraph (/Users/____/.atom/packages/atomic-emacs/lib/atomic-emacs.coffee:224:58)
  at atom-text-editor.<anonymous> (/Users/____/.atom/packages/atomic-emacs/lib/atomic-emacs.coffee:53:83)
  at atom-text-editor.handler (/Users/____/Downloads/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:115:32)
  at atom-text-editor.jQuery.event.dispatch (/Users/____/Downloads/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-text-editor.elemData.handle (/Users/____/Downloads/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/____/Downloads/Atom.app/Contents/Resources/app/src/command-registry.js:246:29)
  at /Users/____/Downloads/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Users/____/Downloads/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Users/____/Downloads/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Users/____/Downloads/Atom.app/Contents/Resources/app/src/window-event-handler.js:182:20)

```

### Commands

```
  7x -0:50.7 atomic-emacs:next-line (atom-text-editor.editor.is-focused)
  3x -0:48.6 atomic-emacs:forward-paragraph (atom-text-editor.editor.is-focused)
  2x -0:47.2 atomic-emacs:backward-paragraph (atom-text-editor.editor.is-focused)
  2x -0:46.0 atomic-emacs:forward-paragraph (atom-text-editor.editor.is-focused)
     -0:30.3 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:30.3 snippets:expand (atom-text-editor.editor.is-focused)
     -0:30.3 editor:indent (atom-text-editor.editor.is-focused)
     -0:24.9 editor:newline (atom-text-editor.editor.is-focused)
  5x -0:21.0 atomic-emacs:forward-paragraph (atom-text-editor.editor.is-focused)
  6x -0:17.4 atomic-emacs:backward-paragraph (atom-text-editor.editor.is-focused)
     -0:15.0 editor:newline (atom-text-editor.editor.is-focused)
  3x -0:14.4 atomic-emacs:backward-paragraph (atom-text-editor.editor.is-focused)
  6x -0:13.6 atomic-emacs:forward-paragraph (atom-text-editor.editor.is-focused)
     -0:11.3 core:backspace (atom-text-editor.editor.is-focused)
     -0:10.7 atomic-emacs:backward-paragraph (atom-text-editor.editor.is-focused)
  2x -0:10.3 atomic-emacs:forward-paragraph (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-handlebars, v0.4.0
atomic-emacs, v0.4.0
linter, v0.12.0
linter-javac, v0.1.3
minimap, v4.5.0

# Dev
No dev packages
```

**Comment by oggy** [comment]
Confirmed -- thanks for reporting!
