### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getCursors' of undefined

### ISSUE THREAD

**Issue by h12o** [avendael/atomic-emacs#54]
steps to reproduce below:

1. Press Command+ and go to "Settings"
2. Press Command+T and show the prompt of the project name
3. Press Esc and this error is occured

**Atom Version**: 0.190.0
**System**: Mac OS X 10.10.3
**Thrown From**: [atomic-emacs](https://github.com/avendael/atomic-emacs) package, v0.5.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getCursors' of undefined

```
At /Users/h12o/.atom/packages/atomic-emacs/lib/atomic-emacs.coffee:21

TypeError: Cannot read property 'getCursors' of undefined
  at deactivateCursors (/Users/h12o/.atom/packages/atomic-emacs/lib/atomic-emacs.coffee:21:3)
  at AtomicEmacs.keyboardQuit (/Users/h12o/.atom/packages/atomic-emacs/lib/atomic-emacs.coffee:91:5)
  at atom-text-editor.disposables.add.atom.commands.add.core:cancel (/Users/h12o/.atom/packages/atomic-emacs/lib/atomic-emacs.coffee:283:45)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:242:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:521:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:356:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:180:20)

```

### Commands

```
     -2:14.5 settings-view:open (atom-text-editor.editor.is-focused)
     -2:13.4 pane:show-previous-item (div.settings-view.pane-item)
     -2:12.8 core:close (atom-text-editor.editor.is-focused)
     -2:10.5 fuzzy-finder:toggle-file-finder (div.settings-view.pane-item)
     -2:09.2 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -2:09.2 core:cancel (atom-text-editor.editor.mini.is-focused)
     -2:08.1 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -2:08.1 core:cancel (atom-text-editor.editor.mini.is-focused)
     -1:52.2 fuzzy-finder:toggle-file-finder (div.settings-view.pane-item)
     -1:50.2 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:50.2 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:02.5 fuzzy-finder:toggle-file-finder (div.settings-view.pane-item)
     -0:01.4 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:01.4 core:cancel (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "solarized-light-syntax"
    ],
    "projectHome": "/Users/h12o/Documents/Git/github.com/h12o",
    "followSymlinks": true
  }
}
```

### Installed Packages

```coffee
# User
atom-lint, v0.20.1
atomic-emacs, v0.5.0
autocomplete-emojis, v2.1.2
autocomplete-paths, v1.0.2
autocomplete-plus, v2.9.0
autocomplete-snippets, v1.2.0
dash, v1.1.0
file-icons, v1.5.4
git-log, v0.3.0
japanese-dictionary, v0.2.0
japanese-menu, v0.4.0
japanese-wrap, v0.2.7
keyboard-localization, v1.2.0
linter, v0.12.0
linter-shellcheck, v0.0.7
localization, v1.16.1
minimap-git-diff, v4.1.2
recent-files, v0.3.0
script, v2.18.0
show-ideographic-space, v0.1.6
space-tab, v0.1.0
web-view, v0.3.0

# Dev
No dev packages
```

**Comment by oggy** [comment]
I can't reproduce this, so assuming it's fixed. Let us know if you're still seeing issues -- thanks!
