### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by noblejasper** [avendael/atomic-emacs#70]
[Enter steps to reproduce below:]

1. ... Ctrl-n -> error!

**Atom Version**: 0.208.0
**System**: Mac OS X 10.10.3
**Thrown From**: [atomic-emacs](https://github.com/avendael/atomic-emacs) package, v0.7.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/jasper/git/noblejasper/dotfiles/macosx/atom/packages/atomic-emacs/lib/atomic-emacs.coffee:29

TypeError: undefined is not a function
  at AtomicEmacs.editor (/Users/jasper/git/noblejasper/dotfiles/macosx/atom/packages/atomic-emacs/lib/atomic-emacs.coffee:29:20)
  at AtomicEmacs.nextLine (/Users/jasper/git/noblejasper/dotfiles/macosx/atom/packages/atomic-emacs/lib/atomic-emacs.coffee:164:6)
  at atom-text-editor.disposables.add.atom.commands.add.atomic-emacs:next-line (/Users/jasper/git/noblejasper/dotfiles/macosx/atom/packages/atomic-emacs/lib/atomic-emacs.coffee:311:56)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
     -0:01.1.0 atomic-emacs:next-line (input.hidden-input)
```

### Config

```json
{
  "core": {
    "followSymlinks": true,
    "themes": [
      "seti-ui",
      "monokai"
    ],
    "ignoredNames": [
      ".git",
      ".bundle",
      ".sass-cache",
      "vendor"
    ],
    "disabledPackages": [
      "atom-alignment",
      "language-csharp",
      "sort-lines",
      "atom-color-highlight"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.3.0
atom-jinja2, v0.5.0
atomic-emacs, v0.7.0
autocomplete-elixir, v1.3.5
compass, v0.9.1
emmet, v2.3.10
japanese-wrap, v0.2.10
javascript-snippets, v1.0.0
language-elixir, v0.5.1
linter, v0.12.7
linter-elixirc, v0.2.2
linter-jshint, v0.1.6
linter-python-pyflakes, v0.1.0
monokai, v0.14.0
seti-ui, v0.7.1
symbols-tree-view, v0.9.3
visual-bell, v1.0.0

# Dev
No dev packages
```

**Comment by bassu** [comment]
Same for `Ctrl-X Ctrl-S`

**Comment by oggy** [comment]
I'm guessing these are fixed now, with the 1.0 compatibility work. Please reopen if see this with the latest versions. Thanks for reporting!

**Comment by zamiang** [comment]
Just saw this today in Atom and it linked me here.

**Comment by quiddle** [comment]
[Enter steps to reproduce below:]

1. ... Ctrl-Space -> Error!

**Atom Version**: 1.0.11
**System**: Mac OS X 10.10.5
**Thrown From**: [atomic-emacs](https://github.com/avendael/atomic-emacs) package, v0.7.2


### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/thaddeus/.atom/packages/atomic-emacs/lib/mark.coffee:63

TypeError: undefined is not a function
  at Mark.deactivate (/Users/thaddeus/.atom/packages/atomic-emacs/lib/mark.coffee:49:23)
  at Mark.set (/Users/thaddeus/.atom/packages/atomic-emacs/lib/mark.coffee:26:6)
  at AtomicEmacs.setMark (/Users/thaddeus/.atom/packages/atomic-emacs/lib/atomic-emacs.coffee:144:24)
  at atom-text-editor.disposables.add.atom.commands.add.atomic-emacs:set-mark (/Users/thaddeus/.atom/packages/atomic-emacs/lib/atomic-emacs.coffee:345:55)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)

```

### Commands

```
     -1:46.6.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  5x -1:45.2.0 core:undo (atom-text-editor.editor.is-focused)
     -1:41 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -1:40.8.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:27.6.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -1:22.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:21.2.0 core:save (atom-text-editor.editor.is-focused)
  2x -1:18.6.0 core:move-up (atom-text-editor.editor.is-focused)
  4x -1:18.1.0 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
  2x -1:16.2.0 pane:show-previous-item (atom-text-editor.editor.is-focused)
     -1:12 settings-view:open (atom-text-editor.editor.is-focused)
     -0:30.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:02.8.0 core:move-to-top (atom-text-editor.editor.is-focused)
     -0:02.1.0 core:move-to-bottom (atom-text-editor.editor.is-focused)
     -0:01.1.0 atomic-emacs:set-mark (atom-text-editor.editor.is-focused)
  3x -0:00.6.0 atomic-emacs:previous-line (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store",
      "node_modules"
    ],
    "disabledPackages": [
      "archive-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atomic-emacs, v0.7.2
editorconfig, v1.1.1
project-manager, v2.3.0

# Dev
No dev packages
```

**Comment by johand** [comment]
### Atom 1.0.11

C-e command not work properly. this show me the "Find in current buffer" option, so every time  i press the C-g to close it an **Uncaught TypeError: undefined is not a function** . it appears,  i must close the editor and reopen
```
TypeError: undefined is not a function
    at Mark.deactivate (/home/foo/.atom/packages/atomic-emacs/lib/mark.coffee:63:36)
    at deactivateCursors (/home/foo/.atom/packages/atomic-emacs/lib/atomic-emacs.coffee:37:41)
    at AtomicEmacs.keyboardQuit (/home/foo/.atom/packages/atomic-emacs/lib/atomic-emacs.coffee:231:14)
    at atom-text-editor.disposables.add.atom.commands.add.core:cancel (/home/foo/.atom/packages/atomic-emacs/lib/atomic-emacs.coffee:618:30)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:245:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
    at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:184:20)
```

**Comment by deanmalmgren** [comment]
I just updated to the most recent atomic-emacs 0.7.2 in atom 1.0.11 and I had an error that redirected here. On OSX, I'm running into this issue after I <kbd>cmd</kbd>+<kbd>F</kbd> to open the search and replace dialog, I see this error when I hit <kbd>esc</kbd>, which normally closes the search and replace dialog. 

```
TypeError: undefined is not a function
    at Mark.deactivate (/Users/foo/.atom/packages/atomic-emacs/lib/mark.coffee:63:36)
    at deactivateCursors (/Users/foo/.atom/packages/atomic-emacs/lib/atomic-emacs.coffee:22:22)
    at AtomicEmacs.keyboardQuit (/Users/foo/.atom/packages/atomic-emacs/lib/atomic-emacs.coffee:147:5)
    at atom-text-editor.disposables.add.atom.commands.add.core:cancel (/Users/foo/.atom/packages/atomic-emacs/lib/atomic-emacs.coffee:350:45)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
    at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)
```

**Comment by oggy** [comment]
Thanks guys. I just pushed the fix out (v0.7.3) -- upgrading atomic-emacs should fix it.

**Comment by deanmalmgren** [comment]
thanks @oggy. that fixed it!

**Comment by johand** [comment]
:metal:

**Comment by noblejasper** [comment]
:+1:
