### ISSUE TITLE
Uncaught Error: This TextEditor has been destroyed

### ISSUE THREAD

**Issue by jmangt** [avendael/atomic-emacs#76]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [atomic-emacs](https://github.com/avendael/atomic-emacs) package, v0.7.1

### Stack Trace

Uncaught Error: This TextEditor has been destroyed

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:745

Error: This TextEditor has been destroyed
  at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1098:15)
  at Marker.module.exports.Marker.getHeadScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:179:33)
  at Cursor.module.exports.Cursor.getScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:127:26)
  at Cursor.module.exports.Cursor.getScreenRange (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:734:20)
  at Cursor.module.exports.Cursor.autoscroll (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:739:51)
  at Selection.module.exports.Selection.autoscroll (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:923:28)
  at Selection.module.exports.Selection.clear (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:206:14)
  at Cursor.module.exports.Cursor.clearSelection (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:675:55)
  at Mark.deactivate (/Users/jalvarez/.atom/packages/atomic-emacs/lib/mark.coffee:48:13)
  at /Users/jalvarez/.atom/packages/atomic-emacs/lib/mark.coffee:38:10
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.applyChange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:626:20)
  at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:777:16)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:743:14)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1151:26)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:772:24
  at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2017:18)
  at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1987:35)
  at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:770:19)
  at TextEditor.module.exports.TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:733:19)
  at TextEditor.object.(anonymous function) [as insertText] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
  at TextEditor.module.exports.TextEditor.insertNewline (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:751:19)
  at TextEditor.object.(anonymous function) [as insertNewline] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
  at TextEditor.atom.commands.add.stopEventPropagationAndGroupUndo.editor:newline (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:626:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:320:34
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:740:18)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1151:26)
  at atom-text-editor.newCommandListeners.(anonymous function) (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:319:22)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
     -6:58.3.0 window:focus-next-pane (atom-text-editor.editor.is-focused)
     -6:57.1.0 pane:close (atom-text-editor.editor.is-focused)
  4x -6:56 atomic-emacs:next-line (atom-text-editor.editor.is-focused)
     -6:51.4.0 core:save (atom-text-editor.editor.is-focused)
 33x -6:46.6.0 atomic-emacs:next-line (atom-text-editor.editor.is-focused)
  6x -6:42.2.0 atomic-emacs:previous-line (atom-text-editor.editor.is-focused)
  2x -6:40.2.0 atomic-emacs:next-line (atom-text-editor.editor.is-focused)
 43x -6:39.4.0 atomic-emacs:previous-line (atom-text-editor.editor.is-focused)
 54x -6:34.9.0 atomic-emacs:next-line (atom-text-editor.editor.is-focused)
 13x -6:29.6.0 atomic-emacs:previous-line (atom-text-editor.editor.is-focused)
     -6:20.7.0 pane:split-right (atom-text-editor.editor.is-focused)
     -0:09.6.0 atomic-emacs:next-line (atom-text-editor.editor.is-focused)
  2x -0:08.7.0 atomic-emacs:previous-line (atom-text-editor.editor.is-focused)
 53x -0:08.2.0 atomic-emacs:next-line (atom-text-editor.editor.is-focused)
  6x -0:02.8.0 atomic-emacs:previous-line (atom-text-editor.editor.is-focused)
  2x -0:01.3.0 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "projectHome": "/Users/jalvarez/Projects",
    "themes": [
      "one-dark-ui",
      "jellybeans"
    ],
    "disabledPackages": [
      "atom-ctags"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.7
atomic-emacs, v0.7.1
go-plus, v3.3.12
jellybeans, v1.3.0
language-docker, v1.1.3
linter, v1.2.3
linter-rubocop, v0.2.7
linter-ruby, v0.1.6
project-manager, v1.15.11

# Dev
No dev packages
```

**Comment by oggy** [comment]
@jmangt Thanks for the report. Could you provide any further hints for reproducing this? I've been unsuccessful so far.

**Comment by johnjcamilleri** [comment]
This seems to happen when:

1. You split the screen (e.g. with `ctrl-x 2`), creating two open tabs of the current file
1. You close the new tab, or collapse the entire pane (e.g. `ctrl-x 1`)
1. You try to edit the contents of the original tab

**Comment by oggy** [comment]
@johnjcamilleri Perfect -- thanks!

**Comment by andrewvc** [comment]
@oggy I've also experienced this with a split editor. I don't actually need to alter the contents of the second pane, just execute any keystroke (like the up arrow).

Closing the second pane then reopening doesn't fix anything. Atom must be restarted.

**Comment by zubko** [comment]
I'm also seeing this error.
For me it happens when I use context menu in Tree View to create a new folder and then I press `ESC` key to cancel the popup. If I cancel the popup by clicking outside of it, then nothing happens.
